language: java
jdk:
  - oraclejdk8
script: "mvn cobertura:cobertura"
sudo: required
cache:
  directories:
    - $HOME/.m2

after_success:
  # test coverage reporting
  - bash <(curl -s https://codecov.io/bash)